image: docker:stable

services:
    - docker:stable-dind

variables:
    REPOSITORY: "${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
    OS: "ubuntu"
    OS_VERSION: "16.04"

before_script:
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"

stages:
    - base
    - glvnd

.base_template: &base_definition
    stage: base
    script:
    - docker pull "${REPOSITORY}:base-${OS}${OS_VERSION}" || true
    - docker build --pull -t "${REPOSITORY}:base-${OS}${OS_VERSION}"
                   --cache-from "${REPOSITORY}:base-${OS}${OS_VERSION}"
                   --build-arg "from=${OS}:${OS_VERSION}"
                   "base/"
    - if [[ "${NO_OS_SUFFIX}" == true ]]; then
          docker tag "${REPOSITORY}:base-${OS}${OS_VERSION}" "${REPOSITORY}:base";
      fi
    - docker push "${REPOSITORY}"

.glvnd_template: &glvnd_definition
    stage: glvnd
    script:
    - VERSION="${CI_JOB_NAME:1}"
    - docker pull "${REPOSITORY}:${VERSION}-runtime-${OS}${OS_VERSION}" || true
    - docker build --pull -t "${REPOSITORY}:${VERSION}-runtime-${OS}${OS_VERSION}"
                   --cache-from "${REPOSITORY}:${VERSION}-runtime-${OS}${OS_VERSION}"
                   --build-arg "from=${REPOSITORY}:base-${OS}${OS_VERSION}"
                   --build-arg "LIBGLVND_VERSION=${LIBGLVND_VERSION}"
                   "glvnd/runtime"
    - docker pull "${REPOSITORY}:${VERSION}-devel-${OS}${OS_VERSION}" || true
    - docker build -t "${REPOSITORY}:${VERSION}-devel-${OS}${OS_VERSION}"
                   --cache-from "${REPOSITORY}:${VERSION}-devel-${OS}${OS_VERSION}"
                   --build-arg "from=${REPOSITORY}:${VERSION}-runtime-${OS}${OS_VERSION}"
                   "glvnd/devel"
    - if [[ "${NO_OS_SUFFIX}" == true ]]; then
          docker tag "${REPOSITORY}:${VERSION}-runtime-${OS}${OS_VERSION}" "${REPOSITORY}:${VERSION}-runtime";
          docker tag "${REPOSITORY}:${VERSION}-devel-${OS}${OS_VERSION}" "${REPOSITORY}:${VERSION}-devel";
      fi
    - if [[ "${LATEST}" == true ]]; then
          docker tag "${REPOSITORY}:${VERSION}-runtime" "${REPOSITORY}:runtime";
          docker tag "${REPOSITORY}:${VERSION}-devel" "${REPOSITORY}:devel";
      fi
    - docker push "${REPOSITORY}"

base:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *base_definition

v1.0-glvnd:
    variables:
        LIBGLVND_VERSION: "v1.0.0"
        NO_OS_SUFFIX: "true"
    <<: *glvnd_definition

v1.1-glvnd:
    variables:
        LIBGLVND_VERSION: "v1.1.0"
        NO_OS_SUFFIX: "true"
        LATEST: "true"
    <<: *glvnd_definition
